# Generated by Django 4.2.10 on 2024-02-15 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_post_blog_date_alter_post_title_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='blog_date',
            new_name='post_date',
        ),
    ]
