# Generated by Django 4.2.10 on 2024-02-16 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0009_post_drafts_post_publish'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='drafts',
            new_name='draft',
        ),
    ]
